namespace: argocd

bases:
#- https://github.com/argoproj/argo-cd//manifests/cluster-install?ref=v1.6.1

# additional resources like ingress rules, cluster and repository secrets.
resources:
- base/namespace.yaml
- base/install.yaml
- base/repos-secrets.yaml
- base/app-argocd.yaml
- base/project.yaml

# changes to config maps
patchesStrategicMerge:
- overlays/argocd-cm.yaml
- overlays/argocd-server.yaml
