apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: repos-secrets
  namespace: argocd
#labels:
#  app.kubernetes.io/name: argocd-secret
#  app.kubernetes.io/part-of: argocd
spec:
  backendType: systemManager
  data:
    - key: /common/github/accesstoken
      name: common-github-accesstoken
    - key: /common/github/username
      name: common-github-username
