---
apiVersion: v1
kind: Namespace
metadata:
  name: "sample"
---
apiVersion: v1
kind: Service
metadata:
  name: "service"
  namespace: "sample"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app: "sample-wp"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "ingress"
  namespace: "sample"
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-1:828381224373:certificate/8a7893e3-8374-4af1-874b-6e323d4acdc5
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    #alb.ingress.kubernetes.io/inbound-cidrs: xxx.xxx.xxx.xxx/32
    alb.ingress.kubernetes.io/security-groups: alb # sg-xxxx、nameOfSg1、nameOfSg2
  labels:
    app: ingress
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
    - host: sample-wp.megunlabo.net
      http:
        paths:
          - path: /*
            backend:
              serviceName: "service"
              servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "sample-wp"
  namespace: "sample"
spec:
  selector:
    matchLabels:
      app: "sample-wp"
  replicas: 1
  template:
    metadata:
      labels:
        app: "sample-wp"
    spec:
      containers:
      - image: wordpress:latest
        imagePullPolicy: Always
        name: "sample-wp"
        ports:
          - containerPort: 80
        env:
          - name: WORDPRESS_DB_HOST
            valueFrom:
              secretKeyRef:
                name: ssm-wp
                key: WORDPRESS_DB_HOST
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: ssm-wp
                key: WORDPRESS_DB_NAME
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: ssm-wp
                key: WORDPRESS_DB_USER
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ssm-wp
                key: WORDPRESS_DB_PASSWORD
          #- name: WORDPRESS_DB_HOST
          #  #value: auroa-serverless.private:3306
          #  value: aurora-cluster.cluster-cikmsai75eum.ap-northeast-1.rds.#amazonaws.com:3306
          #- name: WORDPRESS_DB_NAME
          #  value: wordpress
          #- name: WORDPRESS_DB_USER
          #  value: wordpress
          #- name: WORDPRESS_DB_PASSWORD
          #  value: wordpress
          # CREATE DATABASE wordpress;
          # CREATE USER wordpress IDENTIFIED BY 'wordpress';
          # GRANT ALL ON wordpress.* TO 'wordpress'@'%';
