---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ssm-wp
  namespace: "sample"
spec:
  backendType: systemManager
  # optional: specify role to assume when retrieving the data
  #roleArn: arn:aws:iam::123456789012:role/test-role
  data:
    - key: /rds/endpoint
      name: WORDPRESS_DB_HOST
    - key: /rds/wp/dbname
      name: WORDPRESS_DB_NAME
    - key: /rds/wp/user
      name: WORDPRESS_DB_USER
    - key: /rds/wp/pass
      name: WORDPRESS_DB_PASSWORD
