apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - url: https://github.com/megun/kubernetes-samples.git
      passwordSecret:
        name: repos-secrets
        key: common-github-accesstoken
      usernameSecret:
        name: repos-secrets
        key: common-github-username
